branch-defaults:
  main:
    environment: DUNGEONHELPER-env
    group_suffix: null
global:
  application_name: db_dh
  branch: null
  default_ec2_keyname: dungeon_30102024
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
